import type { Tour, Invoice, CompanySettings } from '../models/domain.models';
import type { DetectedInvoice, OutlookAccount } from '../models/outlook.models';

export const DEMO_SETTINGS: CompanySettings = {
  language: 'en',
  invoiceCounter: 12,
  companyName: 'Good Vienna Tours GmbH',
  companyAddress: 'Stephansplatz 1',
  cityCountry: '1010 Wien, Austria',
  vatNumber: 'ATU12345678',
  logoPath: '',
  defaultVatPercentage: 13,
  bankName: 'Erste Bank',
  accountHolder: 'Good Vienna Tours GmbH',
  iban: 'AT12 2011 1234 5678 9012',
  bic: 'GIBAATWWXXX',
  legalForm: 'GmbH',
  headquarters: 'Wien',
  courtRegistry: 'Handelsgericht Wien',
  registrationNumber: 'FN 123456 a',
  invoiceFooterText: 'Thank you for choosing Good Vienna Tours! We look forward to welcoming you again.',
};

export const DEMO_TOURS: Tour[] = [
  {
    id: 'tour-001',
    name: 'Vienna Classic Walking Tour',
    description: 'Explore the historic heart of Vienna: St. Stephen\'s Cathedral, the Hofburg Imperial Palace, and the baroque streets of the 1st district.',
    meetingPoint: 'Stephansplatz, in front of the Haas Haus',
    basePriceNet: 12.00,
    vatPercentage: 13,
    createdAt: '2024-01-10T09:00:00.000Z',
    updatedAt: '2024-01-10T09:00:00.000Z',
  },
  {
    id: 'tour-002',
    name: 'Imperial Vienna & Schönbrunn',
    description: 'Discover the grandeur of the Habsburg Empire. Visit Schönbrunn Palace gardens, the Ringstrasse boulevard, and the Vienna State Opera.',
    meetingPoint: 'Schönbrunn Palace main gate (U4 Schönbrunn exit)',
    basePriceNet: 15.00,
    vatPercentage: 13,
    createdAt: '2024-01-12T10:00:00.000Z',
    updatedAt: '2024-01-12T10:00:00.000Z',
  },
  {
    id: 'tour-003',
    name: 'Vienna Coffee House Culture Tour',
    description: 'Step into Vienna\'s legendary coffee house tradition. Visit Café Central, Café Landtmann, and Café Schwarzenberg while learning about Viennese café culture.',
    meetingPoint: 'Café Central entrance, Herrengasse 14',
    basePriceNet: 10.00,
    vatPercentage: 13,
    createdAt: '2024-02-01T08:00:00.000Z',
    updatedAt: '2024-02-01T08:00:00.000Z',
  },
  {
    id: 'tour-004',
    name: 'Naschmarkt Food & Culture Tour',
    description: 'Taste your way through Vienna\'s famous open-air market. Sample local cheeses, cured meats, spices, and pastries while learning about Austrian food culture.',
    meetingPoint: 'Naschmarkt, Stand 1 (U4 Kettenbrückengasse exit)',
    basePriceNet: 18.00,
    vatPercentage: 13,
    createdAt: '2024-02-15T11:00:00.000Z',
    updatedAt: '2024-02-15T11:00:00.000Z',
  },
  {
    id: 'tour-005',
    name: 'Ringstrasse Architecture Tour',
    description: 'A deep dive into Vienna\'s monumental Ringstrasse boulevard. Explore the Parliament, City Hall, Burgtheater, and the twin museums of art and natural history.',
    meetingPoint: 'Maria-Theresien-Platz, between the two museums',
    basePriceNet: 14.00,
    vatPercentage: 13,
    createdAt: '2024-03-01T09:30:00.000Z',
    updatedAt: '2024-03-01T09:30:00.000Z',
  },
];

export const DEMO_INVOICES: Invoice[] = [
  {
    id: 'inv-001',
    invoiceNumber: '260401-1030-001',
    invoiceDate: '2026-04-01',
    salutation: 'herr',
    customerName: 'James Wilson',
    customerAddress: '14 Baker Street, London W1U 7BW, UK',
    customerEmail: 'james.wilson@email.com',
    tourDate: '2026-04-01',
    meetingPoint: 'Stephansplatz, in front of the Haas Haus',
    pax: 4,
    guide: 'Sophie Müller',
    paymentMethod: 'cash',
    language: 'en',
    status: 'finalized',
    lineItems: [
      {
        id: 'li-001-1',
        tourId: 'tour-001',
        description: 'Vienna Classic Walking Tour – 4 persons',
        quantity: 4,
        unitPriceNet: 12.00,
        vatPercentage: 13,
        lineTotalNet: 48.00,
        lineTotalVat: 6.24,
        lineTotalGross: 54.24,
        sortOrder: 0,
      },
    ],
    vatBreakdown: [{ vatPercentage: 13, netTotal: 48.00, vatAmount: 6.24, grossTotal: 54.24 }],
    totalNet: 48.00,
    totalVat: 6.24,
    totalGross: 54.24,
    createdAt: '2026-04-01T10:30:00.000Z',
    updatedAt: '2026-04-01T10:30:00.000Z',
  },
  {
    id: 'inv-002',
    invoiceNumber: '260403-1445-002',
    invoiceDate: '2026-04-03',
    salutation: 'frau',
    customerName: 'Marie Dupont',
    customerAddress: '8 Rue de Rivoli, 75001 Paris, France',
    customerEmail: 'marie.dupont@example.fr',
    companyName: 'Dupont Voyages SARL',
    companyAddress: '8 Rue de Rivoli',
    companyCityCountry: '75001 Paris, France',
    tourDate: '2026-04-03',
    meetingPoint: 'Schönbrunn Palace main gate (U4 Schönbrunn exit)',
    pax: 8,
    guide: 'Thomas Bauer',
    civitatisId: 'CIV-20260403-042',
    paymentMethod: 'civitatis',
    language: 'en',
    status: 'finalized',
    lineItems: [
      {
        id: 'li-002-1',
        tourId: 'tour-002',
        description: 'Imperial Vienna & Schönbrunn – 8 persons',
        quantity: 8,
        unitPriceNet: 15.00,
        vatPercentage: 13,
        lineTotalNet: 120.00,
        lineTotalVat: 15.60,
        lineTotalGross: 135.60,
        sortOrder: 0,
      },
    ],
    vatBreakdown: [{ vatPercentage: 13, netTotal: 120.00, vatAmount: 15.60, grossTotal: 135.60 }],
    totalNet: 120.00,
    totalVat: 15.60,
    totalGross: 135.60,
    createdAt: '2026-04-03T14:45:00.000Z',
    updatedAt: '2026-04-03T14:45:00.000Z',
  },
  {
    id: 'inv-003',
    invoiceNumber: '260408-0900-003',
    invoiceDate: '2026-04-08',
    salutation: null,
    customerName: 'Wanderlust Travel Group',
    customerAddress: 'Kärntner Straße 28, 1010 Wien',
    customerEmail: 'bookings@wanderlust.at',
    companyName: 'Wanderlust Travel Group GmbH',
    companyAddress: 'Kärntner Straße 28',
    companyCityCountry: '1010 Wien, Austria',
    tourDate: '2026-04-08',
    meetingPoint: 'Naschmarkt, Stand 1 (U4 Kettenbrückengasse exit)',
    pax: 12,
    guide: 'Anna Kovacs',
    paymentMethod: 'bank',
    language: 'de',
    status: 'finalized',
    lineItems: [
      {
        id: 'li-003-1',
        tourId: 'tour-004',
        description: 'Naschmarkt Food & Culture Tour – 12 Personen',
        quantity: 12,
        unitPriceNet: 18.00,
        vatPercentage: 13,
        lineTotalNet: 216.00,
        lineTotalVat: 28.08,
        lineTotalGross: 244.08,
        sortOrder: 0,
      },
      {
        id: 'li-003-2',
        tourId: undefined,
        description: 'Audioguide Leihgebühr',
        quantity: 12,
        unitPriceNet: 3.00,
        vatPercentage: 20,
        lineTotalNet: 36.00,
        lineTotalVat: 7.20,
        lineTotalGross: 43.20,
        sortOrder: 1,
      },
    ],
    vatBreakdown: [
      { vatPercentage: 13, netTotal: 216.00, vatAmount: 28.08, grossTotal: 244.08 },
      { vatPercentage: 20, netTotal: 36.00, vatAmount: 7.20, grossTotal: 43.20 },
    ],
    totalNet: 252.00,
    totalVat: 35.28,
    totalGross: 287.28,
    createdAt: '2026-04-08T09:00:00.000Z',
    updatedAt: '2026-04-08T09:00:00.000Z',
  },
  {
    id: 'inv-004',
    invoiceNumber: '260415-1115-004',
    invoiceDate: '2026-04-15',
    salutation: 'herr',
    customerName: 'Hiroshi Tanaka',
    customerAddress: '3-1 Marunouchi, Tokyo 100-0005, Japan',
    customerEmail: 'h.tanaka@example.jp',
    tourDate: '2026-04-15',
    meetingPoint: 'Maria-Theresien-Platz, between the two museums',
    pax: 2,
    guide: 'Sophie Müller',
    paymentMethod: 'mypos',
    language: 'en',
    status: 'finalized',
    lineItems: [
      {
        id: 'li-004-1',
        tourId: 'tour-005',
        description: 'Ringstrasse Architecture Tour – 2 persons',
        quantity: 2,
        unitPriceNet: 14.00,
        vatPercentage: 13,
        lineTotalNet: 28.00,
        lineTotalVat: 3.64,
        lineTotalGross: 31.64,
        sortOrder: 0,
      },
    ],
    vatBreakdown: [{ vatPercentage: 13, netTotal: 28.00, vatAmount: 3.64, grossTotal: 31.64 }],
    totalNet: 28.00,
    totalVat: 3.64,
    totalGross: 31.64,
    createdAt: '2026-04-15T11:15:00.000Z',
    updatedAt: '2026-04-15T11:15:00.000Z',
  },
  {
    id: 'inv-005',
    invoiceNumber: '260420-1600-005',
    invoiceDate: '2026-04-20',
    salutation: 'frau',
    customerName: 'Clara Becker',
    customerAddress: 'Hauptstraße 12, 10827 Berlin, Germany',
    customerEmail: 'clara.becker@mail.de',
    tourDate: '2026-04-21',
    meetingPoint: 'Café Central entrance, Herrengasse 14',
    pax: 3,
    guide: 'Anna Kovacs',
    paymentMethod: 'paypal',
    language: 'de',
    status: 'draft',
    lineItems: [
      {
        id: 'li-005-1',
        tourId: 'tour-003',
        description: 'Vienna Coffee House Culture Tour – 3 Personen',
        quantity: 3,
        unitPriceNet: 10.00,
        vatPercentage: 13,
        lineTotalNet: 30.00,
        lineTotalVat: 3.90,
        lineTotalGross: 33.90,
        sortOrder: 0,
      },
    ],
    vatBreakdown: [{ vatPercentage: 13, netTotal: 30.00, vatAmount: 3.90, grossTotal: 33.90 }],
    totalNet: 30.00,
    totalVat: 3.90,
    totalGross: 33.90,
    createdAt: '2026-04-20T16:00:00.000Z',
    updatedAt: '2026-04-20T16:00:00.000Z',
  },
];

// ─── Outlook / email detection mock data ──────────────────────────────────────

export const DEMO_OUTLOOK_ACCOUNT: OutlookAccount = {
  name: 'Sophie Müller',
  username: 'sophie.mueller@goodviennatours.at',
};

export const DEMO_OUTLOOK_EMAILS: DetectedInvoice[] = [
  {
    messageId: 'demo-email-1',
    attachmentId: 'demo-att-1',
    senderName: 'Civitatis GmbH',
    senderEmail: 'invoices@civitatis.com',
    subject: 'Civitatis – Kommissionsabrechnung April 2026 / Commission statement April 2026',
    receivedAt: new Date(Date.now() - 2 * 3600_000).toISOString(),
    attachmentName: 'civitatis_commission_2026-04.pdf',
    attachmentSize: 84_210,
    confidence: 'high',
    confidenceScore: 92,
    reasons: ['Filename contains "commission"', 'Subject contains "commission"', 'PDF attachment', 'Known partner sender (civitatis)'],
    suggestedSubFolder: '2026/04-April',
  },
  {
    messageId: 'demo-email-2',
    attachmentId: 'demo-att-2',
    senderName: 'Audioguide Wien GmbH',
    senderEmail: 'billing@audioguide-wien.at',
    subject: 'Rechnung RG-2026-042 – Audioguide-Leihgeräte April 2026',
    receivedAt: new Date(Date.now() - 6 * 3600_000).toISOString(),
    attachmentName: 'rechnung_rg-2026-042.pdf',
    attachmentSize: 31_500,
    confidence: 'high',
    confidenceScore: 88,
    reasons: ['Filename contains "rechnung"', 'Subject contains "Rechnung"', 'PDF attachment', 'Known supplier sender'],
    suggestedSubFolder: '2026/04-April',
  },
  {
    messageId: 'demo-email-3',
    attachmentId: 'demo-att-3',
    senderName: 'Viator Partner Network',
    senderEmail: 'partners@viator.com',
    subject: 'Your Viator Payout Summary – April 2026',
    receivedAt: new Date(Date.now() - 24 * 3600_000).toISOString(),
    attachmentName: 'viator_payout_april_2026.pdf',
    attachmentSize: 56_780,
    confidence: 'high',
    confidenceScore: 87,
    reasons: ['Filename contains "payout"', 'PDF attachment', 'Known booking platform sender (viator)'],
    suggestedSubFolder: '2026/04-April',
  },
  {
    messageId: 'demo-email-4',
    attachmentId: 'demo-att-4',
    senderName: 'Wiener Linien',
    senderEmail: 'rechnungen@wienerlinien.at',
    subject: 'Ihre Monatsrechnung April 2026 – Wiener Linien',
    receivedAt: new Date(Date.now() - 2 * 24 * 3600_000).toISOString(),
    attachmentName: 'wl_monatsrechnung_2026-04.pdf',
    attachmentSize: 19_200,
    confidence: 'medium',
    confidenceScore: 62,
    reasons: ['Filename contains "rechnung"', 'Subject contains "Monatsrechnung"', 'PDF attachment'],
    suggestedSubFolder: '2026/04-April',
  },
  {
    messageId: 'demo-email-5',
    attachmentId: 'demo-att-5',
    senderName: 'GetYourGuide AG',
    senderEmail: 'finance@getyourguide.com',
    subject: 'GYG Supplier Invoice #INV-GYG-2026-1847',
    receivedAt: new Date(Date.now() - 3 * 24 * 3600_000).toISOString(),
    attachmentName: 'gyg_invoice_INV-GYG-2026-1847.pdf',
    attachmentSize: 44_100,
    confidence: 'high',
    confidenceScore: 91,
    reasons: ['Filename contains "invoice"', 'Subject contains "Invoice"', 'PDF attachment', 'Known booking platform sender (getyourguide)'],
    suggestedSubFolder: '2026/04-April',
  },
  {
    messageId: 'demo-email-6',
    attachmentId: 'demo-att-6',
    senderName: 'Tourismusverband Wien',
    senderEmail: 'info@wien.info',
    subject: 'Mitgliedschaft 2026 – Unterlagen zur Jahresgebühr',
    receivedAt: new Date(Date.now() - 5 * 24 * 3600_000).toISOString(),
    attachmentName: 'mitgliedschaft_jahresgebuehr_2026.pdf',
    attachmentSize: 28_400,
    confidence: 'medium',
    confidenceScore: 58,
    reasons: ['Filename contains "gebuehr"', 'PDF attachment', 'Subject mentions annual fee'],
    suggestedSubFolder: '2026/04-April',
  },
];
